import { Project, Experience, Education } from "./types";

export const personalInfoData = {
    fullName: "Hassan Sarfraz",
    title: "Frontend Developer & AI Enthusiast",
    bio: "I craft high-performance, cinematic web experiences with a focus on modern aesthetics and technical excellence. With over 3 years of experience in the digital realm, I bridge the gap between complex backend logic and pixel-perfect frontend interfaces.",
    email: "hassan@example.com", // Placeholder
    location: "Faisalabad, Pakistan",
    github: "https://github.com/hassan",
    linkedin: "https://www.linkedin.com/in/hassan-s-101a8978",
    resumeUrl: "/resume.pdf"
};

export const projectsData: Project[] = [
    {
        id: 1,
        title: "D&D Autoworks",
        slug: "d-and-d-autoworks",
        shortDescription: "Family-owned automotive repair shop in Minneapolis serving all vehicle makes and models since 1997.",
        longDescription: "D&D Autoworks is a trusted auto repair destination in Minneapolis, MN. Since 1997, they have provided professional maintenance and repair services for all makes and models, emphasizing high-quality care, long-term reliability, and customer trust.",
        techStack: ["Wordpress", "Elementor", "WP Forms"],
        liveUrl: "https://www.danddautoworks.com",
        githubUrl: null,
        imageUrl: "/uploads/2026/03/dnd.webp",
        category: "Web Development",
        featured: true,
        isVisible: true,
        createdAt: new Date("2024-01-01"),
        sortOrder: 1,
        metaTitle: "D&D Autoworks - Family Owned Auto Repair Since 1997",
        metaDescription: "D&D Autoworks is a family-owned automotive repair shop in Minneapolis serving all makes and models of vehicles since 1997.",
        keywords: "Automotive Repair, Family-owned, Minneapolis, Auto maintenance, Engine repair, Since 1997, All makes and models.",
        gallery: null,
        collaborators: "Faisal Zafar, Bilal",
    },
    {
        id: 2,
        title: "Cheo's Auto Service",
        slug: "cheos-auto-service",
        shortDescription: "Trusted auto shop in Apache Junction offering honest repairs and family-oriented care for all vehicle needs.",
        longDescription: "Cheo's Auto Service is a Raise a Hood Certified shop in Apache Junction, AZ, providing high-quality, honest auto repairs. They specialize in engine and transmission repair, diagnostics, and brakes, ensuring every customer is treated like family.",
        techStack: ["Wordpress", "Elementor", "WP Forms"],
        liveUrl: "https://www.cheosautoservice.com",
        githubUrl: null,
        imageUrl: "/uploads/2026/03/cheosautosservice.webp",
        category: "Web Development",
        featured: true,
        isVisible: true,
        createdAt: new Date("2024-01-02"),
        sortOrder: 2,
        metaTitle: "Cheo's Auto Service – Where Every Customer Feels Like Family.",
        metaDescription: "Trusted auto shop in Apache Junction offering honest repairs and family-oriented care for all your vehicle needs.",
        keywords: "Auto Service, Apache Junction, Engine Repair, Transmission Repair, Electrical, Diagnostics, Brakes, Suspension, Tires, Honest Repairs.",
        gallery: null,
        collaborators: "Faisal Zafar, Bilal",
    },
    {
        id: 3,
        title: "Oriscare",
        slug: "oriscare",
        shortDescription: "Premium dental care by expert Smile Artists focusing on the harmony of oral health and aesthetic beauty.",
        longDescription: "Led by Dr. Lorna Flamer-Caldera and Dr. Thema Hepburn, Oris provides a full range of restorative and preventive dental therapies. They focus on building beautiful smiles on a foundation of optimal health through personalized, high-end care.",
        techStack: ["Wordpress", "Elementor", "WP Forms"],
        liveUrl: "https://www.oriscare.com",
        githubUrl: null,
        imageUrl: "/uploads/2026/03/oriscare.webp",
        category: "Web Development",
        featured: true,
        isVisible: true,
        createdAt: new Date("2024-01-03"),
        sortOrder: 3,
        metaTitle: "Oris Enhanced Oral Health & Beauty",
        metaDescription: "Smile Artist cosmetic dentists trusted by celebrities create natural, confident smiles. Read reviews and discover your perfect smile today.",
        keywords: "Smile Artists, Oral Health, Beauty, Restorative therapies, Preventive therapies, Fillings, Root canals, Extractions, Cosmetic Dentist.",
        gallery: null,
        collaborators: "Faisal Zafar, Bilal",
    },
    {
        id: 4,
        title: "Digital Konnecter Systems",
        slug: "digital-konnecter-systems",
        shortDescription: "Leading I.T integrator in Pakistan providing innovative software solutions to transform and scale your business.",
        longDescription: "Digital Konnecter Systems specializes in structured software development and innovative business solutions. They focus on streamlining complex systems to enhance productivity and drive growth through cutting-edge technology and in-depth research.",
        techStack: ["Nextjs", "Drizzle", "Framer Motion", "UI/UX"],
        liveUrl: "https://www.dks.com.pk",
        githubUrl: null,
        imageUrl: "/uploads/2026/03/dks.webp",
        category: "Web Development",
        featured: true,
        isVisible: true,
        createdAt: new Date("2024-01-04"),
        sortOrder: 4,
        metaTitle: "Digital Konnector Systems - Digital Konnecter Systems",
        metaDescription: "Digital Konnector Systems follows a structured approach to software development, ensuring quality and efficiency at every stage.",
        keywords: "I.T Integrator, Software Development, Innovative IT solutions, System streamlining, Business growth, Software Research.",
        gallery: null,
        collaborators: "Faisal Zafar",
    },
    {
        id: 5,
        title: "Al Makki Al Madni Dialysis Center",
        slug: "al-makki-al-madni-dialysis-center",
        shortDescription: "Non-profit dialysis center in Pakistan providing free and subsidized care for chronic kidney disease patients.",
        longDescription: "Founded by Dr. M. Jamil, MMDC combines expert dialysis care with a mission to help underprivileged CKD patients. Since 2022, they've completed over 10,000 sessions, offering high-quality treatment and hope to those in urgent need.",
        techStack: ["Wordpress", "Elementor", "Adobe Photoshop", "UI/UX"],
        liveUrl: "https://www.mmdcpak.com",
        githubUrl: null,
        imageUrl: "/uploads/2026/03/mmdc.webp",
        category: "Web Development",
        featured: true,
        isVisible: true,
        createdAt: new Date("2024-01-05"),
        sortOrder: 5,
        metaTitle: "Al Makki Al Madni Dialysis Center - MMDC",
        metaDescription: "Non-profit dialysis center in Pakistan providing free and subsidized care for chronic kidney disease (CKD) patients.",
        keywords: "Dialysis Center, Chronic Kidney Disease, CKD, Free dialysis, Subsidized dialysis, Dr. M. Jamil, Pakistan, Health Charity.",
        gallery: null,
        collaborators: "Faisal Zafar, Bilal",
    },
    {
        id: 6,
        title: "Khudii Welfare Organization",
        slug: "khudii-welfare-organization",
        shortDescription: "Pakistan's largest digital welfare platform connecting donors and volunteers to create lasting social impact.",
        longDescription: "Khudii is a pioneering e-community in Pakistan that fosters social welfare by connecting storytellers, donors, and volunteers. It supports diverse programs including health and education, empowering individuals to contribute to a better, more purposeful society.",
        techStack: ["Reactjs", "Tailwind CSS", "Framer Motion", "UI/UX"],
        liveUrl: "https://www.khudii.com",
        githubUrl: null,
        imageUrl: "/uploads/2026/03/khudii.webp",
        category: "Web Development",
        featured: true,
        isVisible: true,
        createdAt: new Date("2024-01-06"),
        sortOrder: 6,
        metaTitle: "Khudii - Pakistan's Largest Digital Welfare Platform | Community Support",
        metaDescription: "Khudii is Pakistan's premier digital welfare platform connecting donors, volunteers, and organizations across health, education, and community development.",
        keywords: "khudii pakistan, digital welfare platform, charity donors, volunteer opportunities, health programs, autism care, social welfare.",
        gallery: null,
        collaborators: "Faisal Zafar, Abu Huraira",
    },
    {
        id: 7,
        title: "Mindzbay",
        slug: "mindzbay",
        shortDescription: "Mindzbay offers an intelligent, Unified Communication Platform (CPaaS) for call centers, omni-chat, and AI solutions.",
        longDescription: "Mindzbay provides a unified communication platform (CPaaS) designed to drive revenue and reputation. Their AI-driven suite features call centers, omni-chat, video, and voice channels, helping businesses transition into the future of unified communication and excellence.",
        techStack: ["Wordpress", "Elementor", "WP Forms"],
        liveUrl: "https://www.mindzbay.com",
        githubUrl: null,
        imageUrl: "/uploads/2026/03/mindzbay.webp",
        category: "Web Development",
        featured: true,
        isVisible: true,
        createdAt: new Date("2024-01-07"),
        sortOrder: 7,
        metaTitle: "Home - Mindzbay",
        metaDescription: "Mindzbay - Driven by creativity and innovation, we merge state-of-the-art design with powerful AI technology to help businesses thrive.",
        keywords: "Unified CRM, CPaaS, AI Communication Platform, Call Center Software, Omni-Chat, Video, Voice.",
        gallery: null,
        collaborators: "Faisal Zafar, Usman",
    },
    {
        id: 8,
        title: "Taryaq Welfare Organization",
        slug: "taryaq-welfare-organization",
        shortDescription: "A premium domain name platform offering a secure and straightforward process for buying or leasing domains.",
        longDescription: "Taryaq.com is currently a specialized domain listing providing a safe and simple way for businesses or individuals to acquire premium domain names. The platform focuses on ensuring a smooth and secure transfer process for all types of domain acquisitions.",
        techStack: ["Wordpress", "Elementor", "WP Forms"],
        liveUrl: "https://www.taryaq.com",
        githubUrl: null,
        imageUrl: "/uploads/2026/03/taryaq.webp",
        category: "Web Development",
        featured: true,
        isVisible: true,
        createdAt: new Date("2024-01-08"),
        sortOrder: 8,
        metaTitle: "taryaq.com",
        metaDescription: "The simple, and safe way to buy domain names. No matter what kind of domain you want to buy or lease, we make the transfer simple and safe.",
        keywords: "buy domain, lease domain, domain transfer, taryaq.com",
        gallery: null,
        collaborators: "Faisal Zafar",
    },
    {
        id: 9,
        title: "Tanzeem e Islami",
        slug: "tanzeem-e-islami",
        shortDescription: "Tanzeem-e-Islami focuses on re-establishing Khilafah through prophetic methodology and Quranic teachings.",
        longDescription: "Founded by Dr. Israr Ahmed, Tanzeem-e-Islami is a Pakistan-based organization dedicated to the revival of Khilafah. It emphasizes Islamic education and social transformation based on the Sunnah to establish a just society according to the methodology of Prophet Muhammad (SAWS).",
        techStack: ["Wordpress", "Elementor", "WP Forms"],
        liveUrl: "https://www.tanzeemeislami.org",
        githubUrl: null,
        imageUrl: "/uploads/2026/03/tanzeem.webp",
        category: "Web Development",
        featured: true,
        isVisible: true,
        createdAt: new Date("2024-01-09"),
        sortOrder: 9,
        metaTitle: "TANZEEM-E-ISLAMI, Pakistan - Working To Re-establish / Re-instate Khilafah By Following The Methodology Of Prophet Muhammad (SAWS)",
        metaDescription: "TANZEEM-E-ISLAMI, Pakistan is working to re-establish / re-instate Khilafah by following the methodology of prophet Muhammad (SAWS).",
        keywords: "Tanzeem-e-Islami, Khilafah, Dr. Israr Ahmed, Islamic Methodology, Quranic Teachings, Pakistan Islamic Movement.",
        gallery: null,
        collaborators: "Faisal Zafar, Bilal",
    },
    {
        id: 10,
        title: "Ali Zaman Portfolio",
        slug: "ali-zaman-portfolio",
        shortDescription: "Engr. Ali Zaman is an expert in Strategic Planning and Supply Chain with over 12 years of operational excellence.",
        longDescription: "Engr. Ali Zaman is a seasoned professional specializing in Strategic Planning, Supply Chain, and Operational Excellence. With international exposure in Singapore and Thailand, he excels in change management, production planning, and business optimization, driving growth and efficiency across industries.",
        techStack: ["Nextjs", "Tailwind CSS", "Framer Motion", "UI/UX"],
        liveUrl: "https://www.alizaman.site",
        githubUrl: null,
        imageUrl: "/uploads/2026/03/alizaman.webp",
        category: "Web Development",
        featured: true,
        isVisible: true,
        createdAt: new Date("2024-01-10"),
        sortOrder: 10,
        metaTitle: "Engr. Ali Zaman | Strategic Planning & Supply Chain Expert",
        metaDescription: "Portfolio of Engr. Ali Zaman, a specialist in Strategic Planning, Supply Chain, and Operational Excellence with 12+ years of experience.",
        keywords: "Ali Zaman, Strategic Planning, Supply Chain, Operations, Production Planning, Change Management, Business Optimization",
        gallery: null,
        collaborators: "Solo Project",
    },
    {
        id: 11,
        title: "Ahmed Zaman Portfolio",
        slug: "ahmed-zaman-portfolio",
        shortDescription: "A result-oriented PPC Officer and Operations Manager specializing in unlocking growth and brand awareness.",
        longDescription: "Ahmed Zaman is a professional PPC Officer and Operations Manager with expertise in production planning and financial accounting. Holding a Master in Commerce and having worked at Stylers International, he focuses on optimizing workflows and driving operational efficiency for small businesses.",
        techStack: ["Nextjs", "Tailwind CSS", "Framer Motion", "UI/UX"],
        liveUrl: "https://ahmed-zaman-portfolio.vercel.app",
        githubUrl: null,
        imageUrl: "/uploads/2026/03/ahmedzaman.webp",
        category: "Web Development",
        featured: true,
        isVisible: true,
        createdAt: new Date("2024-01-11"),
        sortOrder: 11,
        metaTitle: "Ahmed Zaman - PPC Officer & Operations Manager",
        metaDescription: "Ahmed Zaman is a passionate PPC Officer and Operations Manager with a proven track record in production planning and business growth.",
        keywords: "Ahmed Zaman, PPC Officer, Operations Manager, Production Planning, Financial Accounting, Business Growth, Faisalabad",
        gallery: null,
        collaborators: "Solo Project",
    }
];

export const experienceData: Experience[] = [
    {
        id: 1,
        company: "Digital Konnector Systems (DKS)",
        position: "Frontend Developer",
        location: "Lahore",
        startDate: "Nov 2023",
        endDate: "Present",
        responsibilities: "Leading the frontend team in developing scalable Next.js applications.\nImplementing complex animations using Framer Motion and ensuring WCAG compliance.",
        isVisible: true,
        sortOrder: 1
    },
    {
        id: 2,
        company: "Self Employed",
        position: "Full Stack Developer",
        location: "(Part Time)",
        startDate: "2025",
        endDate: "Present",
        responsibilities: "Developed multiple high-traffic e-commerce sites using React and Node.js.\nOptimized site speed by 40%.",
        isVisible: true,
        sortOrder: 2
    },
    {
        id: 3,
        company: "Pseudosquare",
        position: "Internship",
        location: "Lahore",
        startDate: "Jan 2023",
        endDate: "Apr 2024",
        responsibilities: "Developed multiple high-traffic e-commerce sites using React and Node.js.\nOptimized site speed by 40%.",
        isVisible: true,
        sortOrder: 3
    }
];

export const educationData: Education[] = [
    {
        id: 1,
        institution: "Government College University Faisalabad",
        degree: "BS Hons Computer Science",
        fieldOfStudy: "Computer Science",
        startDate: "2018",
        endDate: "2022",
        description: "Focused on Software Engineering, Web Technologies, and Human-Computer Interaction.",
        isVisible: true,
        sortOrder: 1
    },
    {
        id: 2,
        institution: "BISE Fsd",
        degree: "Intermediate",
        fieldOfStudy: "Pre-Engineering",
        startDate: "2015",
        endDate: "2017",
        description: "",
        isVisible: true,
        sortOrder: 2
    },
    {
        id: 3,
        institution: "BISE Fsd",
        degree: "Matriculation",
        fieldOfStudy: "Science",
        startDate: "2012",
        endDate: "2014",
        description: "",
        isVisible: true,
        sortOrder: 3
    }
];

export const skillsData = [
    { id: 1, name: "Next.js", logoSvgOrUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg", proficiencyLevel: 95, isVisible: true, isFeatured: true, sortOrder: 1 },
    { id: 2, name: "React", logoSvgOrUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg", proficiencyLevel: 90, isVisible: true, isFeatured: true, sortOrder: 2 },
    { id: 3, name: "TypeScript", logoSvgOrUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg", proficiencyLevel: 92, isVisible: true, isFeatured: true, sortOrder: 3 },
    { id: 4, name: "Tailwind CSS", logoSvgOrUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg", proficiencyLevel: 98, isVisible: true, isFeatured: true, sortOrder: 4 },
    { id: 5, name: "Node.js", logoSvgOrUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg", proficiencyLevel: 85, isVisible: true, isFeatured: true, sortOrder: 5 },
    { id: 6, name: "MySQL", logoSvgOrUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg", proficiencyLevel: 80, isVisible: true, isFeatured: true, sortOrder: 6 },
    { id: 7, name: "Figma", logoSvgOrUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg", proficiencyLevel: 88, isVisible: true, isFeatured: true, sortOrder: 7 },
    { id: 8, name: "JavaScript", logoSvgOrUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg", proficiencyLevel: 95, isVisible: true, isFeatured: true, sortOrder: 8 },
    { id: 9, name: "HTML5", logoSvgOrUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg", proficiencyLevel: 98, isVisible: true, isFeatured: true, sortOrder: 9 },
    { id: 10, name: "CSS3", logoSvgOrUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg", proficiencyLevel: 96, isVisible: true, isFeatured: true, sortOrder: 10 },
    { id: 11, name: "Git", logoSvgOrUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg", proficiencyLevel: 90, isVisible: true, isFeatured: true, sortOrder: 11 },
];

export const servicesData = [
    {
        id: 1,
        title: "Custom Web Application Development",
        description: "Designing and developing robust, scalable, and tailored web applications from scratch, using modern frameworks like React, Next.js, and Node.js.",
        icon: "window-icon",
        isVisible: true,
        isRecommended: true
    },
    {
        id: 2,
        title: "Frontend Development & UI/UX Implementation",
        description: "Creating highly responsive, visually appealing, and user-centric interfaces. Expertise in translating complex Figma/Adobe XD designs into high-quality code.",
        icon: "paint-brush-icon",
        isVisible: true,
        isRecommended: false
    }
];

export const blogPostsData = [
    {
        id: 1,
        title: "Building Cinematic Web Experiences with Next.js",
        slug: "building-cinematic-web-experiences-with-nextjs",
        excerpt: "Learn how to use Next.js and Framer Motion to create high-performance web applications with stunning animations.",
        content: "Detailed blog post content about cinematic web design...",
        publishedAt: new Date("2024-02-15"),
        isVisible: true,
        tags: ["Next.js", "Frontend", "Animations"]
    }
];

export const siteSettingsData = {
    siteName: "Hassan Portfolio",
    baseUrl: "https://hassansarfraz.online",
    contactEmail: "hassan@example.com"
};

export const sectionContentData = {
    hero: {
        title: "Hero Section",
        content: "Hero content..."
    }
};

export const navigationItemsData = [
    { id: 1, label: "About", path: "#about", isVisible: true, location: "both", sortOrder: 1 },
    { id: 2, label: "Experience", path: "#experience", isVisible: true, location: "both", sortOrder: 2 },
    { id: 3, label: "Projects", path: "#projects", isVisible: true, location: "both", sortOrder: 3 },
    { id: 4, label: "Skills", path: "#technologies", isVisible: true, location: "both", sortOrder: 4 },
    { id: 5, label: "Contact", path: "#contact", isVisible: true, location: "both", sortOrder: 5 },
];
